modName = ARTPE
modId = artpe
modGroup = jp.apple
useModGroupForPublishing = true
autoUpdateBuildScript = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Applepie
enableModernJavaSyntax = false
enableGenericInjection = true
gradleTokenVersion = VERSION
usesMixins = false
usesMixinDebug = false
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false
usesShadowedDependencies = false
minimizeShadowedDependencies = false
relocateShadowedDependencies = true
includeWellKnownRepositories = true
usesMavenPublishing = true
rtmCoordinate = com.github.Kai-Z-JP:KaizPatchX:v1.10.1:dev
customNpcVersion = 16f00225054b265b57db0933aa2952993ccb935e
version = 1.0.0
org.gradle.parallel = true
org.gradle.daemon = false
org.gradle.configuration-cache = false
org.gradle.jvmargs = -Xmx8G -Xms4G -Dfile.encoding=UTF-8 -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8
forceSafeNetty = true